Update USERS.md
argoproj/argo-events pull request #1723
Opened 2022-03-11 08:38 UTC by eriadam

Added bimspot.io to the user list

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

2022-03-11 15:49 UTC, alexec reviewed
Could I please ask:

* Users in in alphabetical order I think?
* Please sign-off your commit. 
* Please use conventional commit message format.

2022-04-03 04:48 UTC, alexec requested changes
changes requested

2022-04-23 08:13 UTC, Emadmojiri approved these changes

2022-04-23 08:14 UTC, Emadmojiri approved these changes

2022-06-30 03:21 UTC, closed without merging